@startuml
left to right direction
skinparam packageStyle rectangle

actor "Felhasználó" as a1

rectangle "TODO" {
    a1 --> (Kártya létrehozása)
    a1 --> (Kártya mozgatása)
    a1 --> (Kártya kidobása)
    a1 --> (Lomtár űrítése)

    (Kártya kidobása) ..> (Lomtárba helyezés) : <>
    (Lomtár űrítése) ..> (Végleges törlés) : <>
}
@enduml
