openapi: 3.0.0
info:
  title: Simple API
  description: API for saving and loading data from a JSON file.
  version: 1.0.0
servers:
  - url: http://localhost:4000
paths:
  /save:
    post:
      summary: Save data to the server
      description: Saves an array of JSON data to a file on the server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: A unique identifier for the item.
                    example: 0
                  title:
                    type: string
                    description: The title of the task.
                    example: test1
                  description:
                    type: string
                    description: A brief description of the task itself.
                    example: something to do
                  color:
                    type: string
                    format: color
                    description: The color of the box.
                    example: '#762323'
                  isInTrash:
                    type: boolean
                    description: Indicates if the item is in trash.
                    example: false
                  pos:
                    type: object
                    properties:
                      x:
                        type: integer
                        description: The x-coordinate position.
                        example: 200
                      y:
                        type: integer
                        description: The y-coordinate position.
                        example: 200
                  
      responses:
        '200':
          description: Data saved successfully.
        '500':
          description: Error saving data.
  /load:
    get:
      summary: Load data from the server
      description: Loads an array of JSON data from a file on the server.
      responses:
        '200':
          description: Returns an array of JSON data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: A unique identifier for the item.
                      example: 0
                    title:
                      type: string
                      description: The title of the task.
                      example: test1
                    description:
                      type: string
                      description: A brief description of the task itself.
                      example: something to do
                    color:
                      type: string
                      format: color
                      description: The color of the box.
                      example: '#762323'
                    isInTrash:
                      type: boolean
                      description: Indicates if the item is in trash.
                      example: false
                    pos:
                      type: object
                      properties:
                        x:
                          type: integer
                          description: The x-coordinate position.
                          example: 200
                        y:
                          type: integer
                          description: The y-coordinate position.
                          example: 200
                    
        '500':
          description: Error loading or parsing data.
